import Head from "next/head";
import { Navbar } from "@/components/Navbar";
import Header from "@/sections/Header";
import Message from "@/sections/Message";
import Team from "@/sections/Team";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Democracia Beta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <Header />
        <Message />
        <Team />
        <Footer />
      </div>
    </>
  );
}
